/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import DB.DB_employee;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author ramy alaa
 */
public class checkTask extends javax.swing.JFrame {

    /**
     * Creates new form checkTask
     */
    int p_id;
    String t_name;
    int id;
    public checkTask(int p_id ,int id,String t_name) {
        initComponents();
        this.p_id=p_id;
        this.t_name=t_name;
        this.id=id;
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Yes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Do You Want to Check This Task?");

        Yes.setText("Yes");
        Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesActionPerformed(evt);
            }
        });

        jButton2.setText("No");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Yes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Yes))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesActionPerformed
      
        try {
            // TODO add your handling code here:
         
             int x = 0;
             double n = 0;
            double p = 0;
            int i = 0;
                   double m = 0;
            //String sql ="update task set check_task = '"+"Completed"+"' where emp_id='"+id+"'and project_id='"+p_id+"' and task_name='"+t_name+"'";
            //int k=s.executeUpdate(sql);
            DB_employee e =new DB_employee();
            int k=e.update("task", "check_task", "Completed", "emp_id", id, "project_id", p_id, "task_name", t_name);
            //String v="select 	no_of_checked_task from project where project_id ='"+p_id+"' ";
             ResultSet r=e.select("no_of_checked_task", "project", "project_id", p_id);
            //ResultSet r=s.executeQuery(v);
           
            while(r.next()){
                x=r.getInt("no_of_checked_task");
            }
            
            x++;
            //System.out.println(r.getInt("no_of_checked_task"));
            System.out.println(x);
            
            //v="update project set no_of_checked_task= '"+x+"' where project_id ='"+p_id+"' ";
           
            
            
            
            int rs= e.update("project", "no_of_checked_task", "project_id",x, p_id);
            if(rs==1){
                JOptionPane.showMessageDialog(null,"Checked Successfully","The Selected Task",JOptionPane.INFORMATION_MESSAGE);
            }
            ViewAndCheckTasks mo =new ViewAndCheckTasks(id);
            mo.setLocation(400, 200);
            mo.setSize(900, 400);
            mo.setVisible(true);
            this.dispose();
            ////String sq="select no_task , no_of_checked_task ,project_id from project  ";
            r=e.select( "no_task","project" ,"project_id", p_id);
                    while(r.next()){
                n=r.getInt("no_task");}
             //r=s.executeQuery(sq);
            r=e.select( "no_of_checked_task","project" ,"project_id", p_id);
                    while(r.next()){
                p=r.getInt("no_of_checked_task");}
           
                
             
                m=(double)(p/n)*100.0;
                System.out.println(m);
                e.update("project","project_completing_percentag","project_id",m,p_id);
               //String h="update project set project_completing_percentag = '"+m+"' where project_id ='"+p_id+"' ";
                 
//                 int l =s.executeUpdate(h);
                 m=n=p=0;
            
             
            
        } catch (SQLException ex) {
            Logger.getLogger(checkTask.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_YesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ViewAndCheckTasks mo =new ViewAndCheckTasks(id);
             mo.setLocation(400, 200);
                mo.setSize(900, 400);
                mo.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Yes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
