/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB_employee;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ramy alaa
 */

public class employee extends javax.swing.JFrame {
int id;
int rs;
ResultSet r;
    /**
     * Creates new form employee
     */
    public employee(int id) {
        initComponents();
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CET = new javax.swing.JButton();
        cet = new javax.swing.JButton();
        VAT = new javax.swing.JButton();
        RV = new javax.swing.JButton();
        VP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("EMPLOYEE HOME ");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CET.setText("Check Entry Time");
        CET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETActionPerformed(evt);
            }
        });

        cet.setText("Check Exit Time");
        cet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetActionPerformed(evt);
            }
        });

        VAT.setText("View & Check Assigned Tasks  ");
        VAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VATActionPerformed(evt);
            }
        });

        RV.setText("Request Vication ");
        RV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RVActionPerformed(evt);
            }
        });

        VP.setText("View Penalties");
        VP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPActionPerformed(evt);
            }
        });

        jLabel2.setText("EMPLOYEE HOME ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CET)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cet))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(VAT)
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CET)
                    .addComponent(cet))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VP)
                    .addComponent(RV))
                .addGap(39, 39, 39)
                .addComponent(VAT)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETActionPerformed
       
    
        
         
        DB_employee d=new DB_employee();
        
        rs = d.insert("time_sheet", "entry_time","date","emp_id", LocalTime.now(),LocalDate.now(), id);
       
        if(rs==1){
            JOptionPane.showMessageDialog(null, "Record has been inserted successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        }
    
    
                                           

      
    }//GEN-LAST:event_CETActionPerformed

    private void RVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RVActionPerformed
        // TODO add your handling code here:
        Requestvacation b =new Requestvacation(id);
        b.setVisible(true);
        
    }//GEN-LAST:event_RVActionPerformed

    private void VPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPActionPerformed
        try {                                   
           
                DB_employee d = new DB_employee ();
               ResultSet res = d.select("penalties", "employee", "emp_id", id);
                String  x = null ;
                while(res.next () ){
                    x=res.getString("penalties"); }       
           res = d.select("penalties_count", "employee", "emp_id", id);
           
            int y = 0;
            while(res.next () ){
                
                y=res.getInt("penalties_count");}
             JOptionPane.showMessageDialog(null,x,"Your Penalties",JOptionPane.INFORMATION_MESSAGE);
             JOptionPane.showMessageDialog(null,y,"The Number Of Penalites",JOptionPane.INFORMATION_MESSAGE);
    
        } catch (SQLException ex) {
        Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
    }
               
    
             
    }//GEN-LAST:event_VPActionPerformed

    private void cetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetActionPerformed
    try {
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        DB_employee l=new DB_employee();
        LocalTime t =LocalTime.now();
        
        
         
                //String sql ="update time_sheet set exit_time='"+t+"' where emp_id= '"+id+"' and date='"+LocalDate.now()+"' " ;
        
        rs = l.update("time_sheet","exit_time","emp_id",t,id,"date",LocalDate.now());
        
        //String e="select entry_time,exit_time  from time_sheet where emp_id= '"+id+"' and date='"+LocalDate.now()+"' ";
        
        r = l.select("entry_time", "exit_time", "time_sheet", id,"emp_id",  LocalDate.now());
        Time  y = null,z = null;
        while(r.next () ){
            y = r.getTime("entry_time");
            z= r.getTime("exit_time");}
       int b=(int) z.getTime();
        int k=(int) y.getTime();
       int m=b-k;
        
         r=l.select("t_hours_per_month", "employee", "emp_id", id);
        double q = 0;
        while(r.next () ){
            q = r.getDouble("t_hours_per_month");
            }
        r=l.select("date", "time_sheet", "emp_id", id);
        Date date =new Date();
        while(r.next () ){
            date = r.getDate("date");
            }
        if(date.getDay()==1){
            q=0;
        }
       
        q+= m/3600000.0;
        l.update("employee", "t_hours_per_month","emp_id" ,q, id);
        if(rs==1){
            JOptionPane.showMessageDialog(null, "Record has been inserted successfully ", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        }
    } catch (SQLException ex) {
        Logger.getLogger(employee.class.getName()).log(Level.SEVERE, null, ex);
    }
     
                                           

      
      
    }//GEN-LAST:event_cetActionPerformed

    private void VATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VATActionPerformed
        // TODO add your handling code here:
        ViewAndCheckTasks h =new ViewAndCheckTasks(id);
        h.setVisible(true);
    }//GEN-LAST:event_VATActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CET;
    private javax.swing.JButton RV;
    private javax.swing.JButton VAT;
    private javax.swing.JButton VP;
    private javax.swing.JButton cet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
