/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB_team_leader;
import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ramy alaa
 */
public class update1 extends javax.swing.JFrame {
 static int ch;
 DB_team_leader e =new DB_team_leader();
    /**
     * Creates new form update1
     */
    public update1(int id) {
        ch=id;
    
        initComponents();
         try {
             
            Class.forName("com.mysql.jdbc.Driver");
            Connection  c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project system","root","");
            Statement s= c.createStatement();
            //String sql ="select * from employee where emp_id='"+id+"'";
            
            
            ResultSet res=e.select("*", "employee", "emp_id", id);
            while(res.next () ){
                ename.setText(res.getString("emp_name"));
                epass.setText(res.getString("password"));
                eid.setText(res.getInt("emp_id") + "");
                eposition.setText(res.getString("position"));
                esalary.setText(res.getDouble("salary") + "");
                etotal.setText(res.getInt("t_hours_per_month") + "");
                evacation.setText(res.getInt("available_vacations") + "");
                p.setText(res.getString("penalties"));
               
                delay.setText(res.getInt("penalties_count") + "");
                ereport.setText(res.getString("report"));
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private update1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

//    private update1() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        epass = new javax.swing.JTextField();
        eposition = new javax.swing.JTextField();
        esalary = new javax.swing.JTextField();
        etotal = new javax.swing.JTextField();
        evacation = new javax.swing.JTextField();
        delay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ereport = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        p = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 90, 60, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Emp_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 25, 70, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total hours / month");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(384, 25, 160, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Position");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 330, 60, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Available Vacations");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 100, 150, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Penalties");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 250, 170, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Number of Penalties");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 170, 160, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Report");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 340, 110, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Salary");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 250, 60, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Password");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 170, 80, 14);

        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        getContentPane().add(eid);
        eid.setBounds(84, 19, 220, 30);

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        getContentPane().add(ename);
        ename.setBounds(90, 90, 220, 30);

        epass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epassActionPerformed(evt);
            }
        });
        getContentPane().add(epass);
        epass.setBounds(90, 170, 220, 30);
        getContentPane().add(eposition);
        eposition.setBounds(90, 330, 220, 30);

        esalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esalaryActionPerformed(evt);
            }
        });
        getContentPane().add(esalary);
        esalary.setBounds(90, 250, 220, 30);

        etotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etotalActionPerformed(evt);
            }
        });
        getContentPane().add(etotal);
        etotal.setBounds(572, 19, 190, 30);

        evacation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evacationActionPerformed(evt);
            }
        });
        getContentPane().add(evacation);
        evacation.setBounds(570, 90, 190, 30);

        delay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delayActionPerformed(evt);
            }
        });
        getContentPane().add(delay);
        delay.setBounds(570, 170, 190, 30);

        ereport.setEditable(false);
        ereport.setColumns(20);
        ereport.setRows(5);
        jScrollPane2.setViewportView(ereport);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(570, 340, 160, 80);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 450, 100, 23);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 450, 100, 23);

        p.setColumns(20);
        p.setRows(5);
        jScrollPane1.setViewportView(p);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 236, 160, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void epassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epassActionPerformed

    private void etotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etotalActionPerformed

    private void evacationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evacationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evacationActionPerformed

    private void delayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
         try {                                         
             
             int m=Integer.parseInt(delay.getText());
             
             // TODO add your handling code here:
             double x =Double.parseDouble(esalary.getText());
             String b=(etotal.toString());
             int n =Integer.parseInt(evacation.getText());
             
             try {
                 Class.forName("com.mysql.jdbc.Driver");
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
             }
             
             
             
             Connection  c = null;
             try {
                 c = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/project system","root","");
             } catch (SQLException ex) {
                 Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
             }
             Statement s = null;
             try {
                 s = c.createStatement();
             } catch (SQLException ex) {
                 Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
             }
//             String sql ="update employee set emp_name = '"+ename.getText()+"' ,"
//                     + "password='"+epass.getText()+"',emp_id='"+ch+"'"
//                     + ",position='"+eposition.getText()+"'"
//                     + " ,salary='"+x+"' ,t_hours_per_month='"+etotal.getText()+"'"
//                     + " ,available_vacations='"+n+"' ,report='"+ereport.getText()+"' "
//                     + "where emp_id ='"+ch+"'";
            
             int rs = 0;
             rs = e.update("employee","emp_name",ename.getText(),"password",epass.getText(),
                     "emp_id",ch,"position",eposition.getText(),"salary",x,
                     "t_hours_per_month",etotal.getText(),"available_vacations",n,"report",
                     ereport.getText(),"emp_id",ch);
             
             //String sq="update employee set penalties='"+p.getText()+"'where emp_id='"+ch+"' ";
             
             int r=0;
             r= e.update("employee","penalties","emp_id",Integer.parseInt(p.getText()),ch);
             if(r!=0){
                // String q="select penalties_count from employee where emp_id='"+ch+"'";
                
                 ResultSet res= e.select("penalties_count", "employee", "emp_id", ch);
                 int y = 0;
                 while(res.next () ){
                     y=res.getInt("penalties_count");
                     
                 }
                 y++;
                 //String p="update employee set penalties_count ='"+y+"'where emp_id='"+ch+"' ";
                 e.update("employee","penalties_count","emp_id",y,ch);
                 //s.executeUpdate(p);
                  JOptionPane.showMessageDialog(null,p, "success", JOptionPane.INFORMATION_MESSAGE);
             }
             if (rs==1){
                 JOptionPane.showMessageDialog(null, "record has been updated successfully", "success", JOptionPane.INFORMATION_MESSAGE);
//             Modify1 mo =new Modify1();
//             mo.setLocation(400, 200);
//                mo.setSize(900, 400);
//                mo.setVisible(true);
this.dispose();

             }
             
         } catch (SQLException ex) {
             Logger.getLogger(update1.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_jButton2ActionPerformed

    
 

 
    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Modify1 m=new Modify1();
        m.setLocation(400, 200);
                m.setSize(900, 400);
                m.setVisible(true);
                this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void esalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new update1().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField delay;
    public javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    public javax.swing.JTextField epass;
    public javax.swing.JTextField eposition;
    private javax.swing.JTextArea ereport;
    public javax.swing.JTextField esalary;
    public javax.swing.JTextField etotal;
    public javax.swing.JTextField evacation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea p;
    // End of variables declaration//GEN-END:variables
}
